name: Build Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install deps
      run: |
        sudo apt-get install -y libevent-dev \
            perl perl-modules libio-socket-inet6-perl libjson-xs-perl \
            libwww-perl \
            libparse-recdescent-perl \
            libprotobuf-c-dev protobuf-c-compiler libprotoc-dev \
            libprotobuf-dev protobuf-compiler cmake \
            libsctp-dev \
            openssl

    - name: configure
      run: |
        cd src
        ./configure

    - name: make
      run: |
        cd src
        make -j4

    - name: make testinstall
      run: |
        cd src
        make testinstall

    - name: Run tests
      run: |
        cd tests
        make test aggrtest

  
